# permissions for end users to view horizontalpodcronscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: horizontalpodcronscaler-viewer-role
rules:
- apiGroups:
  - autoscaling.44smkn.github.io
  resources:
  - horizontalpodcronscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling.44smkn.github.io
  resources:
  - horizontalpodcronscalers/status
  verbs:
  - get
